### ISSUE TITLE
Use `create_mask_analysis` or the UDF instead of `create_mask_job`

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-blobfinder#15]
In the docstring of `libertem_blobfinder.common.utils.feature_vector` and the corresponding test case

**Comment by sk1p** [comment]
The usage in the tests was fixed in #14 - there is still this one, though: https://github.com/LiberTEM/LiberTEM-blobfinder/blob/cdd2173658127ec2e84b0e7333bf901dc73bd410/src/libertem_blobfinder/common/patterns.py#L284 - maybe can be fixed together with #13

**Comment by uellue** [comment]
Fix in #16! :-)
