### ISSUE TITLE
Result invalidity when using PyFFTW in a threaded way

### ISSUE THREAD

**Issue by matbryan52** [LiberTEM/LiberTEM-blobfinder#35]
Uncovered during testing here: https://github.com/LiberTEM/LiberTEM/pull/1170#issuecomment-1013256333 there is a complex failure chain when using PyFFTW in a multi-threaded context while the PyFFTW object cache is enabled ([pyfftw.interfaces.cache.enable()](https://github.com/LiberTEM/LiberTEM-blobfinder/blob/master/src/libertem_blobfinder/base/correlation.py#L16)). Hypothesis is that this was never uncovered before because `InlineJobExecutor` is single-threaded, and `DaskJobExecutor` is process-based (and single-threaded?). Now that both `DelayedJobExecutor` and `ConcurrentJobExecutor` are both fundamentally backed by a `concurrent.futures.ThreadPoolExecutor`, we see the issue.

The effect is on the `corrs` result of [do_correlations](https://github.com/LiberTEM/LiberTEM-blobfinder/blob/master/src/libertem_blobfinder/base/correlation.py#L107), as a consequence the `peak_elevations` and `peak_values` results change (but are never NaN).

Here are some values of `peak_elevations` with pyFFTW and np.fft (also when using the proposed solutions).

```
np.fft:            res['peak_elevations'], min 0.94, mean 0.97, max  1.10
pyfftw no lock:    res['peak_elevations'], min 0.01, mean 8.69, max 62.35
pyfftw with lock:  res['peak_elevations'], min 0.94, mean 0.95, max  0.97
pyfftw nocache:    res['peak_elevations'], min 0.94, mean 0.95, max  0.97
```

`peak_elevations` are used to filter valid results inside [_gridmatching.py_](https://github.com/LiberTEM/LiberTEM/blob/master/src/libertem/analysis/gridmatching.py#L108) `Matcher.fastmatch`. Because the values vary widely, some matching attempts immediately fail because a filter returns insufficient valid matches. The way `Matcher.fastmatch` is coded means this returns a `Match.invalid(corr)` object which gives `np.nan` values for the `a`, `b` and `zero` results for that pixel. (This also explains why I saw an improvement when making the min_weight and min_matches parameters looser).

The `centers` and `refineds` results seem to not change when calculated with threading, making me think that `corrs` contains the same peak positions but with a different scaling. 

Proposed solutions are:

1. Disable the use of the object cache
2. Use and acquire a `threading.Lock` object when inside the function `do_correlations`.
3. Figure out why the pyFFTW cache causes this and propose the solution there (probably quite complicated!)

I've tested the first two, but need to check which has the least-bad performance impact.

All of this was tested using `FastCorrelationUDF` and `FastMatchMixin` but I'd expect similar problems with FullMatch etc.

**Comment by uellue** [comment]
Nice catch! The way to do it "properly" would be to use the native `FFTW` interface of PyFFTW and keep that in the UDF task data?

**Comment by uellue** [comment]
It looks like we just have to disable the cache for `ConcurrentJobExecutor`, `DelayedJobExecutor` and `DaskJobExecutor` since enabling the cache is recommended by pyFFTW, and previously there was no multi-threaded execution in LiberTEM. I'll also add a note to the LiberTEM documentation.

**Comment by uellue** [comment]
@matbryan52 do you want to report this upstream? This should at least be documented for other pyFFTW users.

**Comment by matbryan52** [comment]
> @matbryan52 do you want to report this upstream? This should at least be documented for other pyFFTW users.

I'm trying to put together a minimum example that demonstrates the effect, if I can do that then I will report it.

**Comment by uellue** [comment]
Ok, thx! :-) I'll work on the fix in LiberTEM and the documentation in the meantime. 👍

**Comment by matbryan52** [comment]
> It looks like we just have to disable the cache for `ConcurrentJobExecutor`, `DelayedJobExecutor` and `DaskJobExecutor` since enabling the cache is recommended by pyFFTW, and previously there was no multi-threaded execution in LiberTEM. I'll also add a note to the LiberTEM documentation.

That's one solution, yes, although it might be safer to go the `Lock` route if there is not a lot of overhead (I haven't tested), as that will keep it safe from pretty much anything, and we might keep some of the advantages of the cache in terms of speed. Gotta benchmark.

**Comment by uellue** [comment]
@matbryan52 `libertem-blobfinder` is user code that worked perfectly before and followed recommended practices. LiberTEM always ran things in a single thread. Now we introduce a change in LiberTEM that makes such a perfectly valid user code return invalid results. IMO we should do what we can to keep existing code running, as long as it follows recommended practices and uses our published API. Also, it doesn't fail outright, but returns invalid results, which is a bad kind of bug IMO. We are lucky that it triggers NaNs in this case, which are quite striking.

In that sense, I'd prefer to fix it in LiberTEM even if it creates a performance degradation, publish that in the changelog and documentation, and give hints on how to properly implement pyFFTW processing in a threaded environment. The issue here also doesn't seem to be locking when accessing the cache, but using the cached FFTW object in parallel in several threads: https://pyfftw.readthedocs.io/en/latest/source/pyfftw/interfaces/interfaces.html#module-pyfftw.interfaces.cache

**Comment by uellue** [comment]
Maybe this could help to implement a thread-safe cache in pyFFTW? https://docs.python.org/3/library/threading.html#thread-local-data

**Comment by matbryan52** [comment]
Your comments are fine by me, no worries. Do you want to add the endpoint to enable/disable the cache or should I?

Here is the MWE for reporting upstream: https://gist.github.com/matbryan52/551695391a6ef3fcc2c4b4bbd26acd64

**Comment by uellue** [comment]
> Your comments are fine by me, no worries. Do you want to add the endpoint to enable/disable the cache or should I?
> 
> Here is the MWE for reporting upstream: https://gist.github.com/matbryan52/551695391a6ef3fcc2c4b4bbd26acd64

Nice reproducer! :-) I'm still working on the fix...
