### ISSUE TITLE
Release integrations

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-blobfinder#4]
- [x] PyPI (needs credentials)
- [x] Zenodo (needs some credentials and ID env vars)
- [x] Documentation and GitHub releases (needs token env var)

**Comment by sk1p** [comment]
PyPI is done, only zenodo credentails and IDs are still missing /cc @uellue

**Comment by uellue** [comment]
@sk1p I've set the variables. This should be ready for testing now.

**Comment by sk1p** [comment]
:+1: - we can do a RC once #6 is resolved

**Comment by sk1p** [comment]
Done!
